### ISSUE TITLE
Making a script out of the notebook?

### ISSUE THREAD

**Issue by jilljenn** [dawenl/vae_cf#1]
Thanks a lot for the Jupyter notebook :)
Do you plan to prepare one or several Python files? It would make it easier to run it on remote GPUs.

One possible start: https://stackoverflow.com/a/19779226/827989

**Comment by dawenl** [comment]
I don't have any plan to create separate Python files, but it should be fairly easy. 

If all you want is to run it on remote GPUs, you can still run Jupyter remotely -- that's how I ran experiments since I don't even have GPUs on my laptop.

**Comment by dawenl** [comment]
Closing the issue for now. PRs for separate scripts are welcome!
